// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: continua/api/v1/execution.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_StartAgentExecution_FullMethodName  = "/continua.api.v1.ExecutionService/StartAgentExecution"
	ExecutionService_GetAgentExecution_FullMethodName    = "/continua.api.v1.ExecutionService/GetAgentExecution"
	ExecutionService_ListAgentExecutions_FullMethodName  = "/continua.api.v1.ExecutionService/ListAgentExecutions"
	ExecutionService_SignalAgentExecution_FullMethodName = "/continua.api.v1.ExecutionService/SignalAgentExecution"
	ExecutionService_QueryAgent_FullMethodName           = "/continua.api.v1.ExecutionService/QueryAgent"
	ExecutionService_CancelAgentExecution_FullMethodName = "/continua.api.v1.ExecutionService/CancelAgentExecution"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Execution service for managing agent executions
type ExecutionServiceClient interface {
	// Start a new agent execution
	StartAgentExecution(ctx context.Context, in *StartAgentExecutionRequest, opts ...grpc.CallOption) (*StartAgentExecutionResponse, error)
	// Get an agent execution by ID
	GetAgentExecution(ctx context.Context, in *GetAgentExecutionRequest, opts ...grpc.CallOption) (*GetAgentExecutionResponse, error)
	// List agent executions
	ListAgentExecutions(ctx context.Context, in *ListAgentExecutionsRequest, opts ...grpc.CallOption) (*ListAgentExecutionsResponse, error)
	// Signal a running agent execution
	SignalAgentExecution(ctx context.Context, in *SignalAgentExecutionRequest, opts ...grpc.CallOption) (*SignalAgentExecutionResponse, error)
	// Query agent state without mutation
	QueryAgent(ctx context.Context, in *QueryAgentRequest, opts ...grpc.CallOption) (*QueryAgentResponse, error)
	// Cancel a running agent execution
	CancelAgentExecution(ctx context.Context, in *CancelAgentExecutionRequest, opts ...grpc.CallOption) (*CancelAgentExecutionResponse, error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) StartAgentExecution(ctx context.Context, in *StartAgentExecutionRequest, opts ...grpc.CallOption) (*StartAgentExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAgentExecutionResponse)
	err := c.cc.Invoke(ctx, ExecutionService_StartAgentExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) GetAgentExecution(ctx context.Context, in *GetAgentExecutionRequest, opts ...grpc.CallOption) (*GetAgentExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentExecutionResponse)
	err := c.cc.Invoke(ctx, ExecutionService_GetAgentExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) ListAgentExecutions(ctx context.Context, in *ListAgentExecutionsRequest, opts ...grpc.CallOption) (*ListAgentExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentExecutionsResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ListAgentExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) SignalAgentExecution(ctx context.Context, in *SignalAgentExecutionRequest, opts ...grpc.CallOption) (*SignalAgentExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalAgentExecutionResponse)
	err := c.cc.Invoke(ctx, ExecutionService_SignalAgentExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) QueryAgent(ctx context.Context, in *QueryAgentRequest, opts ...grpc.CallOption) (*QueryAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAgentResponse)
	err := c.cc.Invoke(ctx, ExecutionService_QueryAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) CancelAgentExecution(ctx context.Context, in *CancelAgentExecutionRequest, opts ...grpc.CallOption) (*CancelAgentExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAgentExecutionResponse)
	err := c.cc.Invoke(ctx, ExecutionService_CancelAgentExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
//
// Execution service for managing agent executions
type ExecutionServiceServer interface {
	// Start a new agent execution
	StartAgentExecution(context.Context, *StartAgentExecutionRequest) (*StartAgentExecutionResponse, error)
	// Get an agent execution by ID
	GetAgentExecution(context.Context, *GetAgentExecutionRequest) (*GetAgentExecutionResponse, error)
	// List agent executions
	ListAgentExecutions(context.Context, *ListAgentExecutionsRequest) (*ListAgentExecutionsResponse, error)
	// Signal a running agent execution
	SignalAgentExecution(context.Context, *SignalAgentExecutionRequest) (*SignalAgentExecutionResponse, error)
	// Query agent state without mutation
	QueryAgent(context.Context, *QueryAgentRequest) (*QueryAgentResponse, error)
	// Cancel a running agent execution
	CancelAgentExecution(context.Context, *CancelAgentExecutionRequest) (*CancelAgentExecutionResponse, error)
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) StartAgentExecution(context.Context, *StartAgentExecutionRequest) (*StartAgentExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAgentExecution not implemented")
}
func (UnimplementedExecutionServiceServer) GetAgentExecution(context.Context, *GetAgentExecutionRequest) (*GetAgentExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentExecution not implemented")
}
func (UnimplementedExecutionServiceServer) ListAgentExecutions(context.Context, *ListAgentExecutionsRequest) (*ListAgentExecutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentExecutions not implemented")
}
func (UnimplementedExecutionServiceServer) SignalAgentExecution(context.Context, *SignalAgentExecutionRequest) (*SignalAgentExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalAgentExecution not implemented")
}
func (UnimplementedExecutionServiceServer) QueryAgent(context.Context, *QueryAgentRequest) (*QueryAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAgent not implemented")
}
func (UnimplementedExecutionServiceServer) CancelAgentExecution(context.Context, *CancelAgentExecutionRequest) (*CancelAgentExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAgentExecution not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_StartAgentExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAgentExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).StartAgentExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_StartAgentExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).StartAgentExecution(ctx, req.(*StartAgentExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_GetAgentExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).GetAgentExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_GetAgentExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).GetAgentExecution(ctx, req.(*GetAgentExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_ListAgentExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ListAgentExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ListAgentExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ListAgentExecutions(ctx, req.(*ListAgentExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_SignalAgentExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalAgentExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).SignalAgentExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_SignalAgentExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).SignalAgentExecution(ctx, req.(*SignalAgentExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_QueryAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).QueryAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_QueryAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).QueryAgent(ctx, req.(*QueryAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_CancelAgentExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAgentExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).CancelAgentExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_CancelAgentExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).CancelAgentExecution(ctx, req.(*CancelAgentExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "continua.api.v1.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAgentExecution",
			Handler:    _ExecutionService_StartAgentExecution_Handler,
		},
		{
			MethodName: "GetAgentExecution",
			Handler:    _ExecutionService_GetAgentExecution_Handler,
		},
		{
			MethodName: "ListAgentExecutions",
			Handler:    _ExecutionService_ListAgentExecutions_Handler,
		},
		{
			MethodName: "SignalAgentExecution",
			Handler:    _ExecutionService_SignalAgentExecution_Handler,
		},
		{
			MethodName: "QueryAgent",
			Handler:    _ExecutionService_QueryAgent_Handler,
		},
		{
			MethodName: "CancelAgentExecution",
			Handler:    _ExecutionService_CancelAgentExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "continua/api/v1/execution.proto",
}
