// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: continua/api/v1/recorder.proto

package apiv1

import (
	context "context"
	v1 "github.com/continua-ai/continua/packages/proto-go/continua/events/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecorderService_ListEvents_FullMethodName        = "/continua.api.v1.RecorderService/ListEvents"
	RecorderService_ReplayExecution_FullMethodName   = "/continua.api.v1.RecorderService/ReplayExecution"
	RecorderService_GetExecutionState_FullMethodName = "/continua.api.v1.RecorderService/GetExecutionState"
	RecorderService_WatchEvents_FullMethodName       = "/continua.api.v1.RecorderService/WatchEvents"
)

// RecorderServiceClient is the client API for RecorderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Recorder service for event recording and replay
type RecorderServiceClient interface {
	// List events for an execution
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// Replay an execution
	ReplayExecution(ctx context.Context, in *ReplayExecutionRequest, opts ...grpc.CallOption) (*ReplayExecutionResponse, error)
	// Get execution state at a point in time
	GetExecutionState(ctx context.Context, in *GetExecutionStateRequest, opts ...grpc.CallOption) (*GetExecutionStateResponse, error)
	// Stream events as they occur
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.AgentEvent], error)
}

type recorderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecorderServiceClient(cc grpc.ClientConnInterface) RecorderServiceClient {
	return &recorderServiceClient{cc}
}

func (c *recorderServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, RecorderService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recorderServiceClient) ReplayExecution(ctx context.Context, in *ReplayExecutionRequest, opts ...grpc.CallOption) (*ReplayExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayExecutionResponse)
	err := c.cc.Invoke(ctx, RecorderService_ReplayExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recorderServiceClient) GetExecutionState(ctx context.Context, in *GetExecutionStateRequest, opts ...grpc.CallOption) (*GetExecutionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecutionStateResponse)
	err := c.cc.Invoke(ctx, RecorderService_GetExecutionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recorderServiceClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecorderService_ServiceDesc.Streams[0], RecorderService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, v1.AgentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecorderService_WatchEventsClient = grpc.ServerStreamingClient[v1.AgentEvent]

// RecorderServiceServer is the server API for RecorderService service.
// All implementations must embed UnimplementedRecorderServiceServer
// for forward compatibility.
//
// Recorder service for event recording and replay
type RecorderServiceServer interface {
	// List events for an execution
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// Replay an execution
	ReplayExecution(context.Context, *ReplayExecutionRequest) (*ReplayExecutionResponse, error)
	// Get execution state at a point in time
	GetExecutionState(context.Context, *GetExecutionStateRequest) (*GetExecutionStateResponse, error)
	// Stream events as they occur
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[v1.AgentEvent]) error
	mustEmbedUnimplementedRecorderServiceServer()
}

// UnimplementedRecorderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecorderServiceServer struct{}

func (UnimplementedRecorderServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedRecorderServiceServer) ReplayExecution(context.Context, *ReplayExecutionRequest) (*ReplayExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplayExecution not implemented")
}
func (UnimplementedRecorderServiceServer) GetExecutionState(context.Context, *GetExecutionStateRequest) (*GetExecutionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionState not implemented")
}
func (UnimplementedRecorderServiceServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[v1.AgentEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedRecorderServiceServer) mustEmbedUnimplementedRecorderServiceServer() {}
func (UnimplementedRecorderServiceServer) testEmbeddedByValue()                         {}

// UnsafeRecorderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecorderServiceServer will
// result in compilation errors.
type UnsafeRecorderServiceServer interface {
	mustEmbedUnimplementedRecorderServiceServer()
}

func RegisterRecorderServiceServer(s grpc.ServiceRegistrar, srv RecorderServiceServer) {
	// If the following call pancis, it indicates UnimplementedRecorderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecorderService_ServiceDesc, srv)
}

func _RecorderService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecorderServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecorderService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecorderServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecorderService_ReplayExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecorderServiceServer).ReplayExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecorderService_ReplayExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecorderServiceServer).ReplayExecution(ctx, req.(*ReplayExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecorderService_GetExecutionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecorderServiceServer).GetExecutionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecorderService_GetExecutionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecorderServiceServer).GetExecutionState(ctx, req.(*GetExecutionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecorderService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecorderServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, v1.AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecorderService_WatchEventsServer = grpc.ServerStreamingServer[v1.AgentEvent]

// RecorderService_ServiceDesc is the grpc.ServiceDesc for RecorderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecorderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "continua.api.v1.RecorderService",
	HandlerType: (*RecorderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEvents",
			Handler:    _RecorderService_ListEvents_Handler,
		},
		{
			MethodName: "ReplayExecution",
			Handler:    _RecorderService_ReplayExecution_Handler,
		},
		{
			MethodName: "GetExecutionState",
			Handler:    _RecorderService_GetExecutionState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _RecorderService_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "continua/api/v1/recorder.proto",
}
