#!/usr/bin/env python3
"""Generate Python types from OpenAPI spec."""

import subprocess
import sys
from pathlib import Path

import yaml


def apply_nullable_ref_fixes(openapi_path: Path, output_path: Path) -> None:
    """Patch datamodel-code-generator output for required nullable ref fields.

    The generator currently drops nullable ref semantics for required object
    refs, whether they are expressed via legacy `nullable` / `x-nullable` on
    `allOf: [$ref: ...]` or via OpenAPI 3.1 `anyOf: [$ref, {type: "null"}]`.
    We preserve those semantics here by reading the OpenAPI schema and
    rewriting the generated field annotations to `T | None` while keeping the
    fields required.
    """

    spec = yaml.safe_load(openapi_path.read_text())
    schemas = spec.get("components", {}).get("schemas", {})
    nullable_ref_fields: dict[str, dict[str, str]] = {}

    for schema_name, schema in schemas.items():
        properties = schema.get("properties", {})
        for field_name, field_schema in properties.items():
            ref: str | None = None

            if field_schema.get("nullable") or field_schema.get("x-nullable"):
                refs = field_schema.get("allOf")
                if isinstance(refs, list) and len(refs) == 1:
                    candidate_ref = refs[0].get("$ref")
                    if isinstance(candidate_ref, str):
                        ref = candidate_ref

            if ref is None:
                refs = field_schema.get("anyOf")
                if isinstance(refs, list) and len(refs) == 2:
                    has_null_variant = any(
                        item.get("type") == "null" for item in refs if isinstance(item, dict)
                    )
                    ref_variants = [
                        item.get("$ref")
                        for item in refs
                        if isinstance(item, dict) and isinstance(item.get("$ref"), str)
                    ]
                    if has_null_variant and len(ref_variants) == 1:
                        ref = ref_variants[0]

            if ref is None or not ref.startswith("#/components/schemas/"):
                continue

            target_type = ref.rsplit("/", 1)[-1]
            nullable_ref_fields.setdefault(schema_name, {})[field_name] = target_type

    if not nullable_ref_fields:
        return

    lines = output_path.read_text().splitlines()
    current_class: str | None = None
    patched_lines: list[str] = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("class ") and stripped.endswith("(BaseModel):"):
            current_class = stripped.split()[1].split("(")[0]
        elif stripped and not line.startswith(" "):
            current_class = None

        if current_class and current_class in nullable_ref_fields:
            for field_name, target_type in nullable_ref_fields[current_class].items():
                prefix = f"    {field_name}: {target_type}"
                if line.startswith(prefix) and "| None" not in line:
                    line = line.replace(prefix, f"{prefix} | None", 1)
                    break

        patched_lines.append(line)

    output_path.write_text("\n".join(patched_lines) + "\n")


def apply_enum_default_fixes(output_path: Path) -> None:
    """Patch generated enum defaults so the SDK remains mypy-clean.

    datamodel-code-generator emits OpenAPI enum defaults as raw strings even
    when the field annotation is the generated Enum class. Pydantic accepts
    those defaults at runtime, but strict mypy correctly flags them.
    """

    replacements = {
        '    status: Status5 | None = "running"': "    status: Status5 | None = Status5.running",
        '    type: Type1 | None = "default"': "    type: Type1 | None = Type1.default",
        '    level: Level | None = "default"': "    level: Level | None = Level.default",
        '    event_type: IngestEventType | None = "log"': (
            "    event_type: IngestEventType | None = IngestEventType.log"
        ),
        '    level: IngestEventLevel | None = "info"': (
            "    level: IngestEventLevel | None = IngestEventLevel.info"
        ),
    }

    text = output_path.read_text()
    for old, new in replacements.items():
        text = text.replace(old, new)
    output_path.write_text(text)


def apply_ruff_header(output_path: Path) -> None:
    """Allow generated OpenAPI descriptions to exceed the project line length."""

    text = output_path.read_text()
    marker = "# ruff: noqa: E501"
    if marker in text:
        return

    header = "# generated by datamodel-codegen:\n#   filename:  openapi.bundle.yaml\n"
    if text.startswith(header):
        text = text.replace(header, f"{header}{marker}\n", 1)
    else:
        text = f"{marker}\n{text}"
    output_path.write_text(text)


def main():
    repo_root = Path(__file__).parent.parent.parent.parent
    openapi_path = repo_root / "contracts" / "openapi" / "openapi.bundle.yaml"
    output_path = Path(__file__).parent.parent / "src" / "continua" / "types.py"

    if not openapi_path.exists():
        print(f"❌ OpenAPI bundle not found: {openapi_path}")
        sys.exit(1)

    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input", str(openapi_path),
        "--output", str(output_path),
        "--input-file-type", "openapi",
        "--disable-timestamp",
        "--output-model-type", "pydantic_v2.BaseModel",
        "--use-schema-description",
        "--field-constraints",
        "--use-double-quotes",
        "--target-python-version", "3.10",
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"❌ Generation failed:\n{result.stderr}")
        sys.exit(1)

    apply_nullable_ref_fixes(openapi_path, output_path)
    apply_enum_default_fixes(output_path)
    apply_ruff_header(output_path)

    print(f"✅ Generated {output_path}")

if __name__ == "__main__":
    main()
