# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from continua.api.v1 import execution_pb2 as continua_dot_api_dot_v1_dot_execution__pb2


class ExecutionServiceStub(object):
    """Execution service for managing agent executions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAgentExecution = channel.unary_unary(
                '/continua.api.v1.ExecutionService/StartAgentExecution',
                request_serializer=continua_dot_api_dot_v1_dot_execution__pb2.StartAgentExecutionRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.StartAgentExecutionResponse.FromString,
                _registered_method=True)
        self.GetAgentExecution = channel.unary_unary(
                '/continua.api.v1.ExecutionService/GetAgentExecution',
                request_serializer=continua_dot_api_dot_v1_dot_execution__pb2.GetAgentExecutionRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.GetAgentExecutionResponse.FromString,
                _registered_method=True)
        self.ListAgentExecutions = channel.unary_unary(
                '/continua.api.v1.ExecutionService/ListAgentExecutions',
                request_serializer=continua_dot_api_dot_v1_dot_execution__pb2.ListAgentExecutionsRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.ListAgentExecutionsResponse.FromString,
                _registered_method=True)
        self.SignalAgentExecution = channel.unary_unary(
                '/continua.api.v1.ExecutionService/SignalAgentExecution',
                request_serializer=continua_dot_api_dot_v1_dot_execution__pb2.SignalAgentExecutionRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.SignalAgentExecutionResponse.FromString,
                _registered_method=True)
        self.QueryAgent = channel.unary_unary(
                '/continua.api.v1.ExecutionService/QueryAgent',
                request_serializer=continua_dot_api_dot_v1_dot_execution__pb2.QueryAgentRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.QueryAgentResponse.FromString,
                _registered_method=True)
        self.CancelAgentExecution = channel.unary_unary(
                '/continua.api.v1.ExecutionService/CancelAgentExecution',
                request_serializer=continua_dot_api_dot_v1_dot_execution__pb2.CancelAgentExecutionRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.CancelAgentExecutionResponse.FromString,
                _registered_method=True)


class ExecutionServiceServicer(object):
    """Execution service for managing agent executions
    """

    def StartAgentExecution(self, request, context):
        """Start a new agent execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentExecution(self, request, context):
        """Get an agent execution by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentExecutions(self, request, context):
        """List agent executions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalAgentExecution(self, request, context):
        """Signal a running agent execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAgent(self, request, context):
        """Query agent state without mutation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAgentExecution(self, request, context):
        """Cancel a running agent execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAgentExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAgentExecution,
                    request_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.StartAgentExecutionRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_execution__pb2.StartAgentExecutionResponse.SerializeToString,
            ),
            'GetAgentExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentExecution,
                    request_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.GetAgentExecutionRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_execution__pb2.GetAgentExecutionResponse.SerializeToString,
            ),
            'ListAgentExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentExecutions,
                    request_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.ListAgentExecutionsRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_execution__pb2.ListAgentExecutionsResponse.SerializeToString,
            ),
            'SignalAgentExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalAgentExecution,
                    request_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.SignalAgentExecutionRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_execution__pb2.SignalAgentExecutionResponse.SerializeToString,
            ),
            'QueryAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAgent,
                    request_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.QueryAgentRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_execution__pb2.QueryAgentResponse.SerializeToString,
            ),
            'CancelAgentExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAgentExecution,
                    request_deserializer=continua_dot_api_dot_v1_dot_execution__pb2.CancelAgentExecutionRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_execution__pb2.CancelAgentExecutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continua.api.v1.ExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('continua.api.v1.ExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionService(object):
    """Execution service for managing agent executions
    """

    @staticmethod
    def StartAgentExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.ExecutionService/StartAgentExecution',
            continua_dot_api_dot_v1_dot_execution__pb2.StartAgentExecutionRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_execution__pb2.StartAgentExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.ExecutionService/GetAgentExecution',
            continua_dot_api_dot_v1_dot_execution__pb2.GetAgentExecutionRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_execution__pb2.GetAgentExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.ExecutionService/ListAgentExecutions',
            continua_dot_api_dot_v1_dot_execution__pb2.ListAgentExecutionsRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_execution__pb2.ListAgentExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignalAgentExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.ExecutionService/SignalAgentExecution',
            continua_dot_api_dot_v1_dot_execution__pb2.SignalAgentExecutionRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_execution__pb2.SignalAgentExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.ExecutionService/QueryAgent',
            continua_dot_api_dot_v1_dot_execution__pb2.QueryAgentRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_execution__pb2.QueryAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAgentExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.ExecutionService/CancelAgentExecution',
            continua_dot_api_dot_v1_dot_execution__pb2.CancelAgentExecutionRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_execution__pb2.CancelAgentExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
