# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from continua.api.v1 import gateway_pb2 as continua_dot_api_dot_v1_dot_gateway__pb2


class GatewayServiceStub(object):
    """Gateway service for health and metadata
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/continua.api.v1.GatewayService/Health',
                request_serializer=continua_dot_api_dot_v1_dot_gateway__pb2.HealthRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_gateway__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/continua.api.v1.GatewayService/GetVersion',
                request_serializer=continua_dot_api_dot_v1_dot_gateway__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_gateway__pb2.GetVersionResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Gateway service for health and metadata
    """

    def Health(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Get server version info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=continua_dot_api_dot_v1_dot_gateway__pb2.HealthRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_gateway__pb2.HealthResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=continua_dot_api_dot_v1_dot_gateway__pb2.GetVersionRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_gateway__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continua.api.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('continua.api.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Gateway service for health and metadata
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.GatewayService/Health',
            continua_dot_api_dot_v1_dot_gateway__pb2.HealthRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_gateway__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.GatewayService/GetVersion',
            continua_dot_api_dot_v1_dot_gateway__pb2.GetVersionRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_gateway__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
