# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: continua/api/v1/gateway.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'continua/api/v1/gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63ontinua/api/v1/gateway.proto\x12\x0f\x63ontinua.api.v1\"\x0f\n\rHealthRequest\"y\n\x0eHealthResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version\x12\x16\n\x06\x63ommit\x18\x03 \x01(\tR\x06\x63ommit\x12\x1d\n\nbuild_time\x18\x04 \x01(\tR\tbuildTime\"\x13\n\x11GetVersionRequest\"\x84\x01\n\x12GetVersionResponse\x12\x18\n\x07version\x18\x01 \x01(\tR\x07version\x12\x16\n\x06\x63ommit\x18\x02 \x01(\tR\x06\x63ommit\x12\x1d\n\nbuild_time\x18\x03 \x01(\tR\tbuildTime\x12\x1d\n\ngo_version\x18\x04 \x01(\tR\tgoVersion2\xb2\x01\n\x0eGatewayService\x12I\n\x06Health\x12\x1e.continua.api.v1.HealthRequest\x1a\x1f.continua.api.v1.HealthResponse\x12U\n\nGetVersion\x12\".continua.api.v1.GetVersionRequest\x1a#.continua.api.v1.GetVersionResponseB\xca\x01\n\x13\x63om.continua.api.v1B\x0cGatewayProtoP\x01ZGgithub.com/continua-ai/continua/packages/proto-go/continua/api/v1;apiv1\xa2\x02\x03\x43\x41X\xaa\x02\x0f\x43ontinua.Api.V1\xca\x02\x0f\x43ontinua\\Api\\V1\xe2\x02\x1b\x43ontinua\\Api\\V1\\GPBMetadata\xea\x02\x11\x43ontinua::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'continua.api.v1.gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.continua.api.v1B\014GatewayProtoP\001ZGgithub.com/continua-ai/continua/packages/proto-go/continua/api/v1;apiv1\242\002\003CAX\252\002\017Continua.Api.V1\312\002\017Continua\\Api\\V1\342\002\033Continua\\Api\\V1\\GPBMetadata\352\002\021Continua::Api::V1'
  _globals['_HEALTHREQUEST']._serialized_start=50
  _globals['_HEALTHREQUEST']._serialized_end=65
  _globals['_HEALTHRESPONSE']._serialized_start=67
  _globals['_HEALTHRESPONSE']._serialized_end=188
  _globals['_GETVERSIONREQUEST']._serialized_start=190
  _globals['_GETVERSIONREQUEST']._serialized_end=209
  _globals['_GETVERSIONRESPONSE']._serialized_start=212
  _globals['_GETVERSIONRESPONSE']._serialized_end=344
  _globals['_GATEWAYSERVICE']._serialized_start=347
  _globals['_GATEWAYSERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
