# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from continua.api.v1 import recorder_pb2 as continua_dot_api_dot_v1_dot_recorder__pb2
from continua.events.v1 import agent_events_pb2 as continua_dot_events_dot_v1_dot_agent__events__pb2


class RecorderServiceStub(object):
    """Recorder service for event recording and replay
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEvents = channel.unary_unary(
                '/continua.api.v1.RecorderService/ListEvents',
                request_serializer=continua_dot_api_dot_v1_dot_recorder__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_recorder__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.ReplayExecution = channel.unary_unary(
                '/continua.api.v1.RecorderService/ReplayExecution',
                request_serializer=continua_dot_api_dot_v1_dot_recorder__pb2.ReplayExecutionRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_recorder__pb2.ReplayExecutionResponse.FromString,
                _registered_method=True)
        self.GetExecutionState = channel.unary_unary(
                '/continua.api.v1.RecorderService/GetExecutionState',
                request_serializer=continua_dot_api_dot_v1_dot_recorder__pb2.GetExecutionStateRequest.SerializeToString,
                response_deserializer=continua_dot_api_dot_v1_dot_recorder__pb2.GetExecutionStateResponse.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/continua.api.v1.RecorderService/WatchEvents',
                request_serializer=continua_dot_api_dot_v1_dot_recorder__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=continua_dot_events_dot_v1_dot_agent__events__pb2.AgentEvent.FromString,
                _registered_method=True)


class RecorderServiceServicer(object):
    """Recorder service for event recording and replay
    """

    def ListEvents(self, request, context):
        """List events for an execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplayExecution(self, request, context):
        """Replay an execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecutionState(self, request, context):
        """Get execution state at a point in time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """Stream events as they occur
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecorderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=continua_dot_api_dot_v1_dot_recorder__pb2.ListEventsRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_recorder__pb2.ListEventsResponse.SerializeToString,
            ),
            'ReplayExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayExecution,
                    request_deserializer=continua_dot_api_dot_v1_dot_recorder__pb2.ReplayExecutionRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_recorder__pb2.ReplayExecutionResponse.SerializeToString,
            ),
            'GetExecutionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutionState,
                    request_deserializer=continua_dot_api_dot_v1_dot_recorder__pb2.GetExecutionStateRequest.FromString,
                    response_serializer=continua_dot_api_dot_v1_dot_recorder__pb2.GetExecutionStateResponse.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=continua_dot_api_dot_v1_dot_recorder__pb2.WatchEventsRequest.FromString,
                    response_serializer=continua_dot_events_dot_v1_dot_agent__events__pb2.AgentEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continua.api.v1.RecorderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('continua.api.v1.RecorderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecorderService(object):
    """Recorder service for event recording and replay
    """

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.RecorderService/ListEvents',
            continua_dot_api_dot_v1_dot_recorder__pb2.ListEventsRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_recorder__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplayExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.RecorderService/ReplayExecution',
            continua_dot_api_dot_v1_dot_recorder__pb2.ReplayExecutionRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_recorder__pb2.ReplayExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecutionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/continua.api.v1.RecorderService/GetExecutionState',
            continua_dot_api_dot_v1_dot_recorder__pb2.GetExecutionStateRequest.SerializeToString,
            continua_dot_api_dot_v1_dot_recorder__pb2.GetExecutionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/continua.api.v1.RecorderService/WatchEvents',
            continua_dot_api_dot_v1_dot_recorder__pb2.WatchEventsRequest.SerializeToString,
            continua_dot_events_dot_v1_dot_agent__events__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
