// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyScopes = "apiKey.Scopes"
)

// Defines values for IngestEventLevel.
const (
	IngestEventLevelDebug   IngestEventLevel = "debug"
	IngestEventLevelError   IngestEventLevel = "error"
	IngestEventLevelInfo    IngestEventLevel = "info"
	IngestEventLevelWarning IngestEventLevel = "warning"
)

// Defines values for IngestEventType.
const (
	IngestEventTypeCustom    IngestEventType = "custom"
	IngestEventTypeError     IngestEventType = "error"
	IngestEventTypeException IngestEventType = "exception"
	IngestEventTypeLog       IngestEventType = "log"
	IngestEventTypeMessage   IngestEventType = "message"
	IngestEventTypeMetric    IngestEventType = "metric"
)

// Defines values for IngestResponseStatus.
const (
	IngestResponseStatusAccepted  IngestResponseStatus = "accepted"
	IngestResponseStatusDuplicate IngestResponseStatus = "duplicate"
	IngestResponseStatusFailed    IngestResponseStatus = "failed"
	IngestResponseStatusOk        IngestResponseStatus = "ok"
)

// Defines values for IngestSpanInputLevel.
const (
	IngestSpanInputLevelDebug   IngestSpanInputLevel = "debug"
	IngestSpanInputLevelDefault IngestSpanInputLevel = "default"
	IngestSpanInputLevelError   IngestSpanInputLevel = "error"
	IngestSpanInputLevelWarning IngestSpanInputLevel = "warning"
)

// Defines values for IngestSpanInputStatus.
const (
	IngestSpanInputStatusCompleted IngestSpanInputStatus = "completed"
	IngestSpanInputStatusFailed    IngestSpanInputStatus = "failed"
	IngestSpanInputStatusRunning   IngestSpanInputStatus = "running"
)

// Defines values for IngestSpanInputType.
const (
	IngestSpanInputTypeAgent      IngestSpanInputType = "agent"
	IngestSpanInputTypeChain      IngestSpanInputType = "chain"
	IngestSpanInputTypeDefault    IngestSpanInputType = "default"
	IngestSpanInputTypeEmbedding  IngestSpanInputType = "embedding"
	IngestSpanInputTypeGeneration IngestSpanInputType = "generation"
	IngestSpanInputTypeLlm        IngestSpanInputType = "llm"
	IngestSpanInputTypeRetrieval  IngestSpanInputType = "retrieval"
	IngestSpanInputTypeTool       IngestSpanInputType = "tool"
)

// Defines values for IngestTraceInputStatus.
const (
	IngestTraceInputStatusCompleted IngestTraceInputStatus = "completed"
	IngestTraceInputStatusFailed    IngestTraceInputStatus = "failed"
	IngestTraceInputStatusRunning   IngestTraceInputStatus = "running"
)

// Defines values for SpanKind.
const (
	AGENT  SpanKind = "AGENT"
	CHAIN  SpanKind = "CHAIN"
	CUSTOM SpanKind = "CUSTOM"
	LLM    SpanKind = "LLM"
	TOOL   SpanKind = "TOOL"
)

// Defines values for SpanStatus.
const (
	SpanStatusCOMPLETED SpanStatus = "COMPLETED"
	SpanStatusFAILED    SpanStatus = "FAILED"
	SpanStatusSCHEDULED SpanStatus = "SCHEDULED"
	SpanStatusSTARTED   SpanStatus = "STARTED"
)

// Defines values for TimelineEventLevel.
const (
	TimelineEventLevelDebug   TimelineEventLevel = "debug"
	TimelineEventLevelError   TimelineEventLevel = "error"
	TimelineEventLevelInfo    TimelineEventLevel = "info"
	TimelineEventLevelWarning TimelineEventLevel = "warning"
)

// Defines values for TimelineEventSource.
const (
	Explicit  TimelineEventSource = "explicit"
	Synthetic TimelineEventSource = "synthetic"
)

// Defines values for TimelineEventType.
const (
	TimelineEventTypeCustom        TimelineEventType = "custom"
	TimelineEventTypeError         TimelineEventType = "error"
	TimelineEventTypeException     TimelineEventType = "exception"
	TimelineEventTypeLog           TimelineEventType = "log"
	TimelineEventTypeMessage       TimelineEventType = "message"
	TimelineEventTypeMetric        TimelineEventType = "metric"
	TimelineEventTypeSpanCompleted TimelineEventType = "span_completed"
	TimelineEventTypeSpanFailed    TimelineEventType = "span_failed"
	TimelineEventTypeSpanStarted   TimelineEventType = "span_started"
)

// Defines values for TimelineResponseTraceStatus.
const (
	TimelineResponseTraceStatusCOMPLETED TimelineResponseTraceStatus = "COMPLETED"
	TimelineResponseTraceStatusFAILED    TimelineResponseTraceStatus = "FAILED"
	TimelineResponseTraceStatusRUNNING   TimelineResponseTraceStatus = "RUNNING"
)

// Defines values for TraceStatus.
const (
	COMPLETED TraceStatus = "COMPLETED"
	FAILED    TraceStatus = "FAILED"
	RUNNING   TraceStatus = "RUNNING"
)

// Defines values for ListTracesParamsStatus.
const (
	ListTracesParamsStatusCompleted ListTracesParamsStatus = "completed"
	ListTracesParamsStatusFailed    ListTracesParamsStatus = "failed"
	ListTracesParamsStatusRunning   ListTracesParamsStatus = "running"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// IngestEventInput defines model for IngestEventInput.
type IngestEventInput struct {
	EventTs   *time.Time       `json:"event_ts,omitempty"`
	EventType *IngestEventType `json:"event_type,omitempty"`

	// IdempotencyKey Optional key for event-level deduplication
	IdempotencyKey *string                 `json:"idempotency_key,omitempty"`
	Level          *IngestEventLevel       `json:"level,omitempty"`
	Message        *string                 `json:"message,omitempty"`
	Payload        *map[string]interface{} `json:"payload,omitempty"`
	Sequence       *int32                  `json:"sequence,omitempty"`

	// SpanId External span identifier
	SpanId string `json:"span_id"`

	// TraceId External trace identifier
	TraceId string `json:"trace_id"`
}

// IngestEventLevel defines model for IngestEventLevel.
type IngestEventLevel string

// IngestEventType defines model for IngestEventType.
type IngestEventType string

// IngestRequest defines model for IngestRequest.
type IngestRequest struct {
	// BatchKey Unique identifier for idempotency. Same batch_key returns success without reprocessing.
	BatchKey string              `json:"batch_key"`
	Events   *[]IngestEventInput `json:"events,omitempty"`
	Spans    *[]IngestSpanInput  `json:"spans,omitempty"`
	Traces   *[]IngestTraceInput `json:"traces,omitempty"`
}

// IngestResponse defines model for IngestResponse.
type IngestResponse struct {
	AcceptedCount *int32    `json:"accepted_count,omitempty"`
	BatchKey      string    `json:"batch_key"`
	Errors        *[]string `json:"errors,omitempty"`
	EventCount    *int32    `json:"event_count,omitempty"`
	RejectedCount *int32    `json:"rejected_count,omitempty"`
	SpanCount     *int32    `json:"span_count,omitempty"`

	// Status Processing status. "accepted" for async mode, "duplicate" indicates the batch was already processed.
	Status     IngestResponseStatus `json:"status"`
	TraceCount *int32               `json:"trace_count,omitempty"`
}

// IngestResponseStatus Processing status. "accepted" for async mode, "duplicate" indicates the batch was already processed.
type IngestResponseStatus string

// IngestSpanInput defines model for IngestSpanInput.
type IngestSpanInput struct {
	CompletionTokens *int64     `json:"completion_tokens,omitempty"`
	Depth            *int32     `json:"depth,omitempty"`
	EndTime          *time.Time `json:"end_time,omitempty"`

	// Input Span input data (any JSON-serializable value)
	Input    interface{}             `json:"input,omitempty"`
	Level    *IngestSpanInputLevel   `json:"level,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Model    *string                 `json:"model,omitempty"`
	Name     string                  `json:"name"`

	// Output Span output data (any JSON-serializable value)
	Output interface{} `json:"output,omitempty"`

	// ParentSpanId External parent span identifier
	ParentSpanId *string `json:"parent_span_id,omitempty"`
	PromptTokens *int64  `json:"prompt_tokens,omitempty"`
	Provider     *string `json:"provider,omitempty"`
	Sequence     *int32  `json:"sequence,omitempty"`

	// SpanId External span identifier
	SpanId        string                 `json:"span_id"`
	StartTime     time.Time              `json:"start_time"`
	Status        *IngestSpanInputStatus `json:"status,omitempty"`
	StatusMessage *string                `json:"status_message,omitempty"`
	TotalCost     *float64               `json:"total_cost,omitempty"`

	// TotalTokens Deprecated compatibility field. total_tokens-only payloads are rejected; provide prompt_tokens and/or completion_tokens for supported rollups.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	TotalTokens *int64 `json:"total_tokens,omitempty"`

	// TraceId External trace identifier
	TraceId string               `json:"trace_id"`
	Type    *IngestSpanInputType `json:"type,omitempty"`
}

// IngestSpanInputLevel defines model for IngestSpanInput.Level.
type IngestSpanInputLevel string

// IngestSpanInputStatus defines model for IngestSpanInput.Status.
type IngestSpanInputStatus string

// IngestSpanInputType defines model for IngestSpanInput.Type.
type IngestSpanInputType string

// IngestTraceInput defines model for IngestTraceInput.
type IngestTraceInput struct {
	EndTime     *time.Time `json:"end_time,omitempty"`
	Environment *string    `json:"environment,omitempty"`

	// Input Trace input data (any JSON-serializable value)
	Input    interface{}             `json:"input,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     *string                 `json:"name,omitempty"`

	// Output Trace output data (any JSON-serializable value)
	Output  interface{} `json:"output,omitempty"`
	Release *string     `json:"release,omitempty"`

	// SessionId External session key. The server resolves/creates the internal session UUID from this value.
	SessionId *string                 `json:"session_id,omitempty"`
	StartTime *time.Time              `json:"start_time,omitempty"`
	Status    *IngestTraceInputStatus `json:"status,omitempty"`
	Tags      *[]string               `json:"tags,omitempty"`

	// TraceId External trace identifier
	TraceId string  `json:"trace_id"`
	UserId  *string `json:"user_id,omitempty"`
}

// IngestTraceInputStatus defines model for IngestTraceInput.Status.
type IngestTraceInputStatus string

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"created_at"`

	// ExternalId Human-readable external session identifier used by SDKs
	ExternalId string                  `json:"external_id"`
	Id         openapi_types.UUID      `json:"id"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Name       *string                 `json:"name,omitempty"`

	// TraceCount Number of traces in this session
	TraceCount *int `json:"trace_count,omitempty"`

	// UserId User identifier for this session
	UserId *string `json:"user_id,omitempty"`
}

// SessionList defines model for SessionList.
type SessionList struct {
	Sessions []Session `json:"sessions"`
	Total    int       `json:"total"`
}

// SizeError Error response for 413 Payload Too Large
type SizeError struct {
	// Error Error message describing the size limit violation
	Error string `json:"error"`
}

// Span defines model for Span.
type Span struct {
	CostUsd      *float32           `json:"cost_usd,omitempty"`
	EndedAt      *time.Time         `json:"ended_at,omitempty"`
	ErrorMessage *string            `json:"error_message,omitempty"`
	Id           openapi_types.UUID `json:"id"`

	// Input Span input payload (any valid JSON)
	Input     interface{}             `json:"input,omitempty"`
	Kind      SpanKind                `json:"kind"`
	LatencyMs *int                    `json:"latency_ms,omitempty"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	Name      string                  `json:"name"`

	// Output Span output payload (any valid JSON)
	Output interface{} `json:"output,omitempty"`

	// ParentSpanId External parent span identifier
	ParentSpanId *string `json:"parent_span_id,omitempty"`

	// SpanId External span identifier (used for parent-child relationships)
	SpanId    string             `json:"span_id"`
	StartedAt time.Time          `json:"started_at"`
	Status    SpanStatus         `json:"status"`
	TokensIn  *int               `json:"tokens_in,omitempty"`
	TokensOut *int               `json:"tokens_out,omitempty"`
	TraceId   openapi_types.UUID `json:"trace_id"`
}

// SpanKind defines model for Span.Kind.
type SpanKind string

// SpanStatus defines model for Span.Status.
type SpanStatus string

// SpanList defines model for SpanList.
type SpanList struct {
	Spans []Span `json:"spans"`
}

// TimelineEvent defines model for TimelineEvent.
type TimelineEvent struct {
	EventType TimelineEventType `json:"event_type"`

	// Id Opaque event identifier. Explicit events use persisted UUIDs; synthetic events use deterministic span-based IDs.
	Id      string              `json:"id"`
	Level   *TimelineEventLevel `json:"level,omitempty"`
	Message *string             `json:"message,omitempty"`

	// Payload Event payload details for explicit events and helper metadata for synthetic events
	Payload *map[string]interface{} `json:"payload,omitempty"`

	// Sequence Explicit-event ordering value used to preserve same-timestamp ingest order. Absent for synthetic events.
	Sequence *int32              `json:"sequence,omitempty"`
	Source   TimelineEventSource `json:"source"`

	// SpanId External span identifier for the related span
	SpanId    *string            `json:"span_id,omitempty"`
	SpanName  *string            `json:"span_name,omitempty"`
	Timestamp time.Time          `json:"timestamp"`
	TraceId   openapi_types.UUID `json:"trace_id"`
}

// TimelineEventLevel defines model for TimelineEventLevel.
type TimelineEventLevel string

// TimelineEventSource defines model for TimelineEventSource.
type TimelineEventSource string

// TimelineEventType defines model for TimelineEventType.
type TimelineEventType string

// TimelineResponse defines model for TimelineResponse.
type TimelineResponse struct {
	Events  []TimelineEvent `json:"events"`
	HasMore bool            `json:"has_more"`

	// NextCursor Opaque cursor for the next page when `has_more` is true
	NextCursor *string `json:"next_cursor,omitempty"`

	// PollCursor Opaque cursor representing the last event included in this response. Use for incremental polling even when `has_more` is false.
	PollCursor  *string                     `json:"poll_cursor,omitempty"`
	TraceStatus TimelineResponseTraceStatus `json:"trace_status"`
}

// TimelineResponseTraceStatus defines model for TimelineResponse.TraceStatus.
type TimelineResponseTraceStatus string

// Trace defines model for Trace.
type Trace struct {
	EndedAt *time.Time `json:"ended_at,omitempty"`

	// ErrorCount Count of failed spans in this trace
	ErrorCount     *int                    `json:"error_count,omitempty"`
	Id             openapi_types.UUID      `json:"id"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	Name           string                  `json:"name"`
	SessionId      *openapi_types.UUID     `json:"session_id,omitempty"`
	StartedAt      time.Time               `json:"started_at"`
	Status         TraceStatus             `json:"status"`
	TotalCostUsd   *float32                `json:"total_cost_usd,omitempty"`
	TotalTokensIn  *int                    `json:"total_tokens_in,omitempty"`
	TotalTokensOut *int                    `json:"total_tokens_out,omitempty"`
}

// TraceStatus defines model for Trace.Status.
type TraceStatus string

// TraceList defines model for TraceList.
type TraceList struct {
	Total  int     `json:"total"`
	Traces []Trace `json:"traces"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTracesParams defines parameters for ListTraces.
type ListTracesParams struct {
	Limit     *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *int                `form:"offset,omitempty" json:"offset,omitempty"`
	SessionId *openapi_types.UUID `form:"session_id,omitempty" json:"session_id,omitempty"`

	// Q Full-text search query (searches trace name and user_id)
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Status Filter by trace status
	Status *ListTracesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// StartTimeFrom Filter traces starting at or after this time
	StartTimeFrom *time.Time `form:"start_time_from,omitempty" json:"start_time_from,omitempty"`

	// StartTimeTo Filter traces starting at or before this time
	StartTimeTo *time.Time `form:"start_time_to,omitempty" json:"start_time_to,omitempty"`

	// UserId Filter by user ID
	UserId *string `form:"user_id,omitempty" json:"user_id,omitempty"`

	// HasErrors Filter traces with errors (error_count > 0)
	HasErrors *bool `form:"has_errors,omitempty" json:"has_errors,omitempty"`

	// MinDurationMs Filter traces with duration >= this value in milliseconds
	MinDurationMs *int64 `form:"min_duration_ms,omitempty" json:"min_duration_ms,omitempty"`
}

// ListTracesParamsStatus defines parameters for ListTraces.
type ListTracesParamsStatus string

// GetTraceEventsParams defines parameters for GetTraceEvents.
type GetTraceEventsParams struct {
	// After Opaque cursor returned by a previous timeline response
	After *string `form:"after,omitempty" json:"after,omitempty"`

	// Limit Maximum number of timeline events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// IngestParams defines parameters for Ingest.
type IngestParams struct {
	// Sync If true, wait for processing to complete before returning
	Sync *bool `form:"sync,omitempty" json:"sync,omitempty"`
}

// IngestJSONRequestBody defines body for Ingest for application/json ContentType.
type IngestJSONRequestBody = IngestRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List sessions
	// (GET /api/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams)
	// Get a session by ID
	// (GET /api/sessions/{id})
	GetSession(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List traces
	// (GET /api/traces)
	ListTraces(w http.ResponseWriter, r *http.Request, params ListTracesParams)
	// Get a trace by ID
	// (GET /api/traces/{id})
	GetTrace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List timeline events for a trace
	// (GET /api/traces/{id}/events)
	GetTraceEvents(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetTraceEventsParams)
	// List spans for a trace
	// (GET /api/traces/{id}/spans)
	ListSpansByTrace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Ingest traces, spans, and events
	// (POST /v1/ingest)
	Ingest(w http.ResponseWriter, r *http.Request, params IngestParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List sessions
// (GET /api/sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a session by ID
// (GET /api/sessions/{id})
func (_ Unimplemented) GetSession(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List traces
// (GET /api/traces)
func (_ Unimplemented) ListTraces(w http.ResponseWriter, r *http.Request, params ListTracesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a trace by ID
// (GET /api/traces/{id})
func (_ Unimplemented) GetTrace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List timeline events for a trace
// (GET /api/traces/{id}/events)
func (_ Unimplemented) GetTraceEvents(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetTraceEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List spans for a trace
// (GET /api/traces/{id}/spans)
func (_ Unimplemented) ListSpansByTrace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ingest traces, spans, and events
// (POST /v1/ingest)
func (_ Unimplemented) Ingest(w http.ResponseWriter, r *http.Request, params IngestParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSessionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTraces operation middleware
func (siw *ServerInterfaceWrapper) ListTraces(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTracesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "session_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "session_id", r.URL.Query(), &params.SessionId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "start_time_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_time_from", r.URL.Query(), &params.StartTimeFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_time_from", Err: err})
		return
	}

	// ------------- Optional query parameter "start_time_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_time_to", r.URL.Query(), &params.StartTimeTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_time_to", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "user_id", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "has_errors" -------------

	err = runtime.BindQueryParameter("form", true, false, "has_errors", r.URL.Query(), &params.HasErrors)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "has_errors", Err: err})
		return
	}

	// ------------- Optional query parameter "min_duration_ms" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_duration_ms", r.URL.Query(), &params.MinDurationMs)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_duration_ms", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTraces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrace operation middleware
func (siw *ServerInterfaceWrapper) GetTrace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTraceEvents operation middleware
func (siw *ServerInterfaceWrapper) GetTraceEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTraceEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTraceEvents(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSpansByTrace operation middleware
func (siw *ServerInterfaceWrapper) ListSpansByTrace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSpansByTrace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ingest operation middleware
func (siw *ServerInterfaceWrapper) Ingest(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params IngestParams

	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", r.URL.Query(), &params.Sync)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sync", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ingest(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{id}", wrapper.GetSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/traces", wrapper.ListTraces)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/traces/{id}", wrapper.GetTrace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/traces/{id}/events", wrapper.GetTraceEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/traces/{id}/spans", wrapper.ListSpansByTrace)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/ingest", wrapper.Ingest)
	})

	return r
}
