# generated by datamodel-codegen:
#   filename:  openapi.bundle.yaml
#   timestamp: 2026-01-04T13:52:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel


class Status(Enum):
    ok = "ok"
    degraded = "degraded"


class HealthResponse(BaseModel):
    status: Status
    version: str


class Error(BaseModel):
    code: str
    message: str


class Status1(Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Trace(BaseModel):
    id: UUID
    session_id: UUID | None = None
    name: str
    status: Status1
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    total_tokens_in: int | None = None
    total_tokens_out: int | None = None
    total_cost_usd: float | None = None
    metadata: dict[str, Any] | None = None


class TraceList(BaseModel):
    traces: list[Trace]
    total: int


class Kind(Enum):
    LLM = "LLM"
    TOOL = "TOOL"
    CHAIN = "CHAIN"
    AGENT = "AGENT"
    CUSTOM = "CUSTOM"


class Status2(Enum):
    SCHEDULED = "SCHEDULED"
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Span(BaseModel):
    id: UUID
    trace_id: UUID
    parent_span_id: UUID | None = None
    name: str
    kind: Kind
    status: Status2
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None
    cost_usd: float | None = None
    latency_ms: int | None = None
    error_message: str | None = None
    metadata: dict[str, Any] | None = None


class SpanList(BaseModel):
    spans: list[Span]


class Session(BaseModel):
    id: UUID
    name: str | None = None
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime


class SessionList(BaseModel):
    sessions: list[Session]
    total: int
