# generated by datamodel-codegen:
#   filename:  openapi.bundle.yaml

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field


class Error(BaseModel):
    code: str
    message: str


class SizeError(BaseModel):
    """
    Error response for 413 Payload Too Large
    """

    error: str = Field(
        ..., description="Error message describing the size limit violation"
    )


class Status(Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Trace(BaseModel):
    id: UUID
    session_id: UUID | None = None
    session_external_id: str | None = None
    name: str
    status: Status
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    total_tokens_in: int | None = None
    total_tokens_out: int | None = None
    total_cost_usd: float | None = None
    error_count: int | None = Field(
        None, description="Count of failed spans in this trace"
    )
    metadata: dict[str, Any] | None = None


class TraceDetail(Trace):
    trace_id: str | None = None
    user_id: str | None = None
    tags: list[str] | None = None
    environment: str | None = None
    release: str | None = None
    input: Any | None = Field(None, description="Trace input payload (any valid JSON)")
    output: Any | None = Field(
        None, description="Trace output payload (any valid JSON)"
    )


class TraceList(BaseModel):
    traces: list[Trace]
    total: int


class Kind(Enum):
    LLM = "LLM"
    TOOL = "TOOL"
    CHAIN = "CHAIN"
    AGENT = "AGENT"
    CUSTOM = "CUSTOM"


class Status1(Enum):
    SCHEDULED = "SCHEDULED"
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Span(BaseModel):
    id: UUID
    trace_id: UUID
    span_id: str = Field(
        ...,
        description="External span identifier (used for parent-child relationships)",
    )
    parent_span_id: str | None = Field(
        None, description="External parent span identifier"
    )
    name: str
    kind: Kind
    status: Status1
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None
    cost_usd: float | None = None
    latency_ms: int | None = None
    error_message: str | None = None
    model: str | None = None
    provider: str | None = None
    input: Any | None = Field(None, description="Span input payload (any valid JSON)")
    input_truncated: bool | None = None
    input_original_size_bytes: int | None = None
    input_truncation_reason: str | None = None
    output: Any | None = Field(None, description="Span output payload (any valid JSON)")
    output_truncated: bool | None = None
    output_original_size_bytes: int | None = None
    output_truncation_reason: str | None = None
    metadata: dict[str, Any] | None = None


class SpanList(BaseModel):
    spans: list[Span]


class Session(BaseModel):
    id: UUID
    external_id: str = Field(
        ..., description="Human-readable external session identifier used by SDKs"
    )
    name: str | None = None
    user_id: str | None = Field(None, description="User identifier for this session")
    trace_count: int | None = Field(
        None, description="Number of traces in this session"
    )
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime


class SessionList(BaseModel):
    sessions: list[Session]
    total: int


class SessionNarrativeSummary(BaseModel):
    total_trace_count: int
    returned_trace_count: int
    truncated: bool
    running_trace_count: int = Field(
        ..., description="Count of traces whose raw status normalizes to RUNNING."
    )
    completed_trace_count: int = Field(
        ..., description="Count of traces whose raw status normalizes to COMPLETED."
    )
    failed_trace_count: int = Field(
        ..., description="Count of traces whose raw status normalizes to FAILED."
    )
    total_cost_usd: float
    total_tokens_in: int
    total_tokens_out: int
    started_at: AwareDatetime = Field(
        ...,
        description="Earliest trace start time in the session, or null when the session has no traces.",
    )
    last_activity_at: AwareDatetime = Field(
        ...,
        description="Approximate session-level last activity timestamp computed from trace-level timestamps only.\nPer-trace latest_activity_at is the authoritative activity timestamp.\n",
    )
    explicit_link_count: int = Field(
        ..., description="Explicit lineage count for the shown narrative only."
    )
    inferred_link_count: int = Field(
        ..., description="Inferred lineage count for the shown narrative only."
    )
    unlinked_trace_count: int = Field(
        ..., description="Unlinked trace count for the shown narrative only."
    )


class Status2(Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Type(Enum):
    explicit = "explicit"
    inferred = "inferred"
    unlinked = "unlinked"


class SessionNarrativeLineage(BaseModel):
    type: Type
    parent_trace_id: str | None = Field(
        None,
        description="External parent trace identifier within the shown narrative when linked.",
    )
    trigger_span_id: str | None = Field(
        None,
        description="Optional external span identifier carried by explicit metadata lineage.",
    )
    link_kind: str | None = Field(
        None, description="Optional metadata-provided lineage classification string."
    )


class ComparisonTooLargeErrorDetail(BaseModel):
    baseline_span_count: int
    candidate_span_count: int
    baseline_semantic_count: int
    candidate_semantic_count: int
    max_spans: int
    max_semantic_events: int


class CompareSessionHeader(BaseModel):
    id: UUID
    external_id: str
    name: str | None = None


class CompareTraceHeader(BaseModel):
    id: UUID
    trace_id: str
    name: str
    status: Status2
    user_id: str | None = None
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    duration_ms: int | None = None
    error_count: int | None = None
    total_cost_usd: float | None = None
    total_tokens_in: int | None = None
    total_tokens_out: int | None = None


class CompareSummary(BaseModel):
    total_spans_baseline: int
    total_spans_candidate: int
    matched_spans: int
    unmatched_baseline_spans: int
    unmatched_candidate_spans: int
    heuristic_matches: int
    duration_delta_ms: int
    tokens_in_delta: int
    tokens_out_delta: int
    cost_delta_usd: float
    total_semantic_baseline: int
    total_semantic_candidate: int


class CompareDiffStatus(Enum):
    unchanged = "unchanged"
    changed = "changed"
    baseline_only = "baseline_only"
    candidate_only = "candidate_only"


class CompareMatchSource(Enum):
    stable_id = "stable_id"
    heuristic = "heuristic"


class CompareSemanticEventType(Enum):
    decision = "decision"
    effect = "effect"
    wait = "wait"


class Status4(Enum):
    SCHEDULED = "SCHEDULED"
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CompareSpanSummary(BaseModel):
    id: UUID
    span_id: str
    parent_span_id: str | None = None
    name: str
    kind: Kind
    status: Status4
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None
    cost_usd: float | None = None
    latency_ms: int | None = None
    error_message: str | None = None
    model: str | None = None


class CompareSemanticSummary(BaseModel):
    id: str
    span_id: str | None = None
    span_name: str | None = None
    event_type: CompareSemanticEventType
    timestamp: AwareDatetime
    message: str | None = None
    payload: dict[str, Any] | None = None


class Status5(Enum):
    running = "running"
    completed = "completed"
    failed = "failed"


class IngestTraceInput(BaseModel):
    trace_id: str = Field(..., description="External trace identifier")
    session_id: str | None = Field(
        None,
        description="External session key. The server resolves/creates the internal session UUID from this value.",
    )
    name: str | None = None
    user_id: str | None = None
    tags: list[str] | None = None
    environment: str | None = None
    release: str | None = None
    metadata: dict[str, Any] | None = None
    input: Any | None = Field(
        None, description="Trace input data (any JSON-serializable value)"
    )
    output: Any | None = Field(
        None, description="Trace output data (any JSON-serializable value)"
    )
    status: Status5 | None = "running"
    start_time: AwareDatetime | None = None
    end_time: AwareDatetime | None = None


class Type1(Enum):
    default = "default"
    llm = "llm"
    tool = "tool"
    agent = "agent"
    chain = "chain"
    retrieval = "retrieval"
    embedding = "embedding"
    generation = "generation"


class Level(Enum):
    debug = "debug"
    default = "default"
    warning = "warning"
    error = "error"


class IngestSpanInput(BaseModel):
    trace_id: str = Field(..., description="External trace identifier")
    span_id: str = Field(..., description="External span identifier")
    parent_span_id: str | None = Field(
        None, description="External parent span identifier"
    )
    name: str
    type: Type1 | None = "default"
    status: Status5 | None = "running"
    status_message: str | None = None
    level: Level | None = "default"
    start_time: AwareDatetime
    end_time: AwareDatetime | None = None
    input: Any | None = Field(
        None, description="Span input data (any JSON-serializable value)"
    )
    output: Any | None = Field(
        None, description="Span output data (any JSON-serializable value)"
    )
    model: str | None = None
    provider: str | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    total_tokens: int | None = Field(
        None,
        deprecated=True,
        description="Deprecated compatibility field. total_tokens-only payloads are rejected; provide prompt_tokens and/or completion_tokens for supported rollups.",
    )
    total_cost: float | None = None
    metadata: dict[str, Any] | None = None
    sequence: int | None = None
    depth: int | None = None


class IngestEventType(Enum):
    log = "log"
    error = "error"
    exception = "exception"
    message = "message"
    metric = "metric"
    custom = "custom"
    state_change = "state_change"
    decision = "decision"
    effect = "effect"
    wait = "wait"
    snapshot_marker = "snapshot_marker"


class IngestEventLevel(Enum):
    debug = "debug"
    info = "info"
    warning = "warning"
    error = "error"


class IngestEventInput(BaseModel):
    trace_id: str = Field(..., description="External trace identifier")
    span_id: str = Field(..., description="External span identifier")
    event_type: IngestEventType | None = "log"
    level: IngestEventLevel | None = "info"
    event_ts: AwareDatetime | None = None
    sequence: int | None = None
    message: str | None = None
    payload: dict[str, Any] | None = Field(
        None,
        description="Free-form event payload. Semantic debugger conventions apply for some event types: `effect` may include reserved `effect_id`; `wait` may include reserved `wait_id`; `state_change` expects `key`, `old_value`, `new_value`, and optional `namespace`; `decision` expects `question`, `chosen`, and optional `alternatives` and `reasoning`; `snapshot_marker` is a debugger milestone event, not a checkpoint or resumability primitive, and conventionally uses `marker_kind` (a non-empty string; default vocabulary `milestone`) and `label` (a human-facing marker label).\n",
    )
    idempotency_key: str | None = Field(
        None, description="Optional key for event-level deduplication"
    )


class TimelineEventType(Enum):
    log = "log"
    error = "error"
    exception = "exception"
    message = "message"
    metric = "metric"
    custom = "custom"
    state_change = "state_change"
    decision = "decision"
    effect = "effect"
    wait = "wait"
    snapshot_marker = "snapshot_marker"
    span_started = "span_started"
    span_completed = "span_completed"
    span_failed = "span_failed"


class TimelineEventSource(Enum):
    explicit = "explicit"
    synthetic = "synthetic"


class TimelineEventLevel(Enum):
    debug = "debug"
    info = "info"
    warning = "warning"
    error = "error"


class TimelineEvent(BaseModel):
    id: str = Field(
        ...,
        description="Opaque event identifier. Explicit events use persisted UUIDs; synthetic events use deterministic span-based IDs.",
    )
    trace_id: UUID
    span_id: str | None = Field(
        None, description="External span identifier for the related span"
    )
    span_name: str | None = None
    event_type: TimelineEventType
    timestamp: AwareDatetime
    source: TimelineEventSource
    level: TimelineEventLevel | None = None
    sequence: int | None = Field(
        None,
        description="Explicit-event ordering value used to preserve same-timestamp ingest order. Absent for synthetic events.",
    )
    message: str | None = None
    payload: dict[str, Any] | None = Field(
        None,
        description="Event payload details for explicit events and helper metadata for synthetic events",
    )


class TraceStatus(Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TimelineResponse(BaseModel):
    events: list[TimelineEvent]
    trace_status: TraceStatus
    has_more: bool
    next_cursor: str | None = Field(
        None, description="Opaque cursor for the next page when `has_more` is true"
    )
    poll_cursor: str | None = Field(
        None,
        description="Opaque cursor representing the last event included in this response. Use for incremental polling even when `has_more` is false.",
    )


class Status7(Enum):
    """
    Processing status. "accepted" for async mode, "duplicate" indicates the batch was already processed.
    """

    ok = "ok"
    accepted = "accepted"
    duplicate = "duplicate"
    failed = "failed"


class IngestResponse(BaseModel):
    status: Status7 = Field(
        ...,
        description='Processing status. "accepted" for async mode, "duplicate" indicates the batch was already processed.',
    )
    batch_key: str
    batch_id: UUID | None = Field(
        None,
        description="Stable batch identifier returned for sync responses, true-async acceptance,\nand duplicates. It may be omitted for the legacy Stage A fake-async path.\n",
    )
    trace_count: int | None = None
    span_count: int | None = None
    event_count: int | None = None
    accepted_count: int | None = None
    rejected_count: int | None = None
    errors: list[str] | None = None


class Status8(Enum):
    accepted = "accepted"
    processing = "processing"
    completed = "completed"
    failed = "failed"


class BatchStatusResponse(BaseModel):
    batch_id: UUID
    batch_key: str
    status: Status8
    attempt_count: int
    server_received_at: AwareDatetime
    processing_started_at: AwareDatetime | None = None
    processing_completed_at: AwareDatetime | None = None
    trace_count: int | None = None
    span_count: int | None = None
    event_count: int | None = None
    accepted_count: int | None = None
    rejected_count: int | None = None
    last_error_code: str | None = None
    last_error_message: str | None = None


class SessionNarrativeTrace(BaseModel):
    id: UUID
    trace_id: str = Field(
        ..., description="External trace identifier for the narrative trace."
    )
    name: str
    status: Status2
    user_id: str | None = None
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    duration_ms: int | None = None
    error_count: int | None = None
    total_cost_usd: float | None = None
    total_tokens_in: int | None = None
    total_tokens_out: int | None = None
    latest_activity_at: AwareDatetime
    semantic_events: list[TimelineEvent] = Field(
        ...,
        description="Explicit decision, effect, and wait events for this trace. SessionNarrativeTrace.trace_id is the\nexternal trace identifier, while each nested semantic_events[].trace_id remains the internal trace UUID\nfrom TimelineEvent.\n",
    )
    lineage: SessionNarrativeLineage


class ComparisonTooLargeError(BaseModel):
    code: str
    message: str
    detail: ComparisonTooLargeErrorDetail


class SemanticDiffGroup(BaseModel):
    event_type: CompareSemanticEventType
    diff_status: CompareDiffStatus
    match_source: CompareMatchSource | None = None
    match_reason: str | None = None
    changed_fields: list[str]
    baseline_event: CompareSemanticSummary | None
    candidate_event: CompareSemanticSummary | None


class IngestRequest(BaseModel):
    batch_key: str = Field(
        ...,
        description="Unique identifier for idempotency. Same batch_key returns success without reprocessing.",
    )
    traces: list[IngestTraceInput] | None = None
    spans: list[IngestSpanInput] | None = None
    events: list[IngestEventInput] | None = None


class SessionNarrativeResponse(BaseModel):
    summary: SessionNarrativeSummary
    traces: list[SessionNarrativeTrace]


class SpanDiffRow(BaseModel):
    diff_status: CompareDiffStatus
    match_source: CompareMatchSource | None = None
    match_reason: str | None = None
    changed_fields: list[str]
    baseline_span: CompareSpanSummary | None
    candidate_span: CompareSpanSummary | None
    semantic_groups: list[SemanticDiffGroup]
    depth: int


class SessionCompareResponse(BaseModel):
    session: CompareSessionHeader
    baseline: CompareTraceHeader
    candidate: CompareTraceHeader
    summary: CompareSummary
    span_diffs: list[SpanDiffRow]
