# generated by datamodel-codegen:
#   filename:  openapi.bundle.yaml
#   timestamp: 2026-03-03T16:54:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field


class Error(BaseModel):
    code: str
    message: str


class SizeError(BaseModel):
    """
    Error response for 413 Payload Too Large
    """

    error: str = Field(
        ..., description="Error message describing the size limit violation"
    )


class Status(Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Trace(BaseModel):
    id: UUID
    session_id: UUID | None = None
    name: str
    status: Status
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    total_tokens_in: int | None = None
    total_tokens_out: int | None = None
    total_cost_usd: float | None = None
    error_count: int | None = Field(
        None, description="Count of failed spans in this trace"
    )
    metadata: dict[str, Any] | None = None


class TraceList(BaseModel):
    traces: list[Trace]
    total: int


class Kind(Enum):
    LLM = "LLM"
    TOOL = "TOOL"
    CHAIN = "CHAIN"
    AGENT = "AGENT"
    CUSTOM = "CUSTOM"


class Status1(Enum):
    SCHEDULED = "SCHEDULED"
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class Span(BaseModel):
    id: UUID
    trace_id: UUID
    span_id: str = Field(
        ...,
        description="External span identifier (used for parent-child relationships)",
    )
    parent_span_id: str | None = Field(
        None, description="External parent span identifier"
    )
    name: str
    kind: Kind
    status: Status1
    started_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None
    cost_usd: float | None = None
    latency_ms: int | None = None
    error_message: str | None = None
    input: Any | None = Field(None, description="Span input payload (any valid JSON)")
    output: Any | None = Field(None, description="Span output payload (any valid JSON)")
    metadata: dict[str, Any] | None = None


class SpanList(BaseModel):
    spans: list[Span]


class Session(BaseModel):
    id: UUID
    external_id: str = Field(
        ..., description="Human-readable external session identifier used by SDKs"
    )
    name: str | None = None
    user_id: str | None = Field(None, description="User identifier for this session")
    trace_count: int | None = Field(
        None, description="Number of traces in this session"
    )
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime


class SessionList(BaseModel):
    sessions: list[Session]
    total: int


class Status2(Enum):
    running = "running"
    completed = "completed"
    failed = "failed"


class IngestTraceInput(BaseModel):
    trace_id: str = Field(..., description="External trace identifier")
    session_id: str | None = Field(
        None,
        description="External session key. The server resolves/creates the internal session UUID from this value.",
    )
    name: str | None = None
    user_id: str | None = None
    tags: list[str] | None = None
    environment: str | None = None
    release: str | None = None
    metadata: dict[str, Any] | None = None
    input: Any | None = Field(
        None, description="Trace input data (any JSON-serializable value)"
    )
    output: Any | None = Field(
        None, description="Trace output data (any JSON-serializable value)"
    )
    status: Status2 | None = "running"
    start_time: AwareDatetime | None = None
    end_time: AwareDatetime | None = None


class Type(Enum):
    default = "default"
    llm = "llm"
    tool = "tool"
    agent = "agent"
    chain = "chain"
    retrieval = "retrieval"
    embedding = "embedding"
    generation = "generation"


class Level(Enum):
    debug = "debug"
    default = "default"
    warning = "warning"
    error = "error"


class IngestSpanInput(BaseModel):
    trace_id: str = Field(..., description="External trace identifier")
    span_id: str = Field(..., description="External span identifier")
    parent_span_id: str | None = Field(
        None, description="External parent span identifier"
    )
    name: str
    type: Type | None = "default"
    status: Status2 | None = "running"
    status_message: str | None = None
    level: Level | None = "default"
    start_time: AwareDatetime
    end_time: AwareDatetime | None = None
    input: Any | None = Field(
        None, description="Span input data (any JSON-serializable value)"
    )
    output: Any | None = Field(
        None, description="Span output data (any JSON-serializable value)"
    )
    model: str | None = None
    provider: str | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    total_tokens: int | None = Field(
        None,
        deprecated=True,
        description="Deprecated compatibility field. total_tokens-only payloads are rejected; provide prompt_tokens and/or completion_tokens for supported rollups.",
    )
    total_cost: float | None = None
    metadata: dict[str, Any] | None = None
    sequence: int | None = None
    depth: int | None = None


class EventType(Enum):
    log = "log"
    error = "error"
    exception = "exception"
    message = "message"
    metric = "metric"
    custom = "custom"


class Level1(Enum):
    debug = "debug"
    info = "info"
    warning = "warning"
    error = "error"


class IngestEventInput(BaseModel):
    trace_id: str = Field(..., description="External trace identifier")
    span_id: str = Field(..., description="External span identifier")
    event_type: EventType | None = "log"
    level: Level1 | None = "info"
    event_ts: AwareDatetime | None = None
    sequence: int | None = None
    message: str | None = None
    payload: dict[str, Any] | None = None
    idempotency_key: str | None = Field(
        None, description="Optional key for event-level deduplication"
    )


class Status4(Enum):
    """
    Processing status. "accepted" for async mode, "duplicate" indicates the batch was already processed.
    """

    ok = "ok"
    accepted = "accepted"
    duplicate = "duplicate"
    failed = "failed"


class IngestResponse(BaseModel):
    status: Status4 = Field(
        ...,
        description='Processing status. "accepted" for async mode, "duplicate" indicates the batch was already processed.',
    )
    batch_key: str
    trace_count: int | None = None
    span_count: int | None = None
    event_count: int | None = None
    accepted_count: int | None = None
    rejected_count: int | None = None
    errors: list[str] | None = None


class IngestRequest(BaseModel):
    batch_key: str = Field(
        ...,
        description="Unique identifier for idempotency. Same batch_key returns success without reprocessing.",
    )
    traces: list[IngestTraceInput] | None = None
    spans: list[IngestSpanInput] | None = None
    events: list[IngestEventInput] | None = None
