# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: continua/common/v1/errors.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'continua/common/v1/errors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63ontinua/common/v1/errors.proto\x12\x12\x63ontinua.common.v1\"\xd0\x01\n\x0c\x45rrorDetails\x12\x1d\n\nerror_type\x18\x01 \x01(\tR\terrorType\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12J\n\x08metadata\x18\x03 \x03(\x0b\x32..continua.common.v1.ErrorDetails.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\x8f\x01\n\x07\x46\x61ilure\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12\x16\n\x06source\x18\x02 \x01(\tR\x06source\x12\x1f\n\x0bstack_trace\x18\x03 \x01(\tR\nstackTrace\x12\x31\n\x05\x63\x61use\x18\x04 \x01(\x0b\x32\x1b.continua.common.v1.FailureR\x05\x63\x61useB\xde\x01\n\x16\x63om.continua.common.v1B\x0b\x45rrorsProtoP\x01ZMgithub.com/continua-ai/continua/packages/proto-go/continua/common/v1;commonv1\xa2\x02\x03\x43\x43X\xaa\x02\x12\x43ontinua.Common.V1\xca\x02\x12\x43ontinua\\Common\\V1\xe2\x02\x1e\x43ontinua\\Common\\V1\\GPBMetadata\xea\x02\x14\x43ontinua::Common::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'continua.common.v1.errors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.continua.common.v1B\013ErrorsProtoP\001ZMgithub.com/continua-ai/continua/packages/proto-go/continua/common/v1;commonv1\242\002\003CCX\252\002\022Continua.Common.V1\312\002\022Continua\\Common\\V1\342\002\036Continua\\Common\\V1\\GPBMetadata\352\002\024Continua::Common::V1'
  _globals['_ERRORDETAILS_METADATAENTRY']._loaded_options = None
  _globals['_ERRORDETAILS_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ERRORDETAILS']._serialized_start=56
  _globals['_ERRORDETAILS']._serialized_end=264
  _globals['_ERRORDETAILS_METADATAENTRY']._serialized_start=205
  _globals['_ERRORDETAILS_METADATAENTRY']._serialized_end=264
  _globals['_FAILURE']._serialized_start=267
  _globals['_FAILURE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
