/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['IBM Plex Mono', 'SFMono-Regular', 'monospace'],
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      colors: {
        'on-secondary': '#ffffff',
        'surface-container': '#eeeeee',
        'tertiary-fixed': '#a9f76d',
        'surface-container-high': '#e8e8e8',
        secondary: '#705d00',
        outline: '#707785',
        'on-secondary-container': '#6e5c00',
        'on-primary-container': '#fefcff',
        'tertiary-fixed-dim': '#8eda54',
        'primary-fixed': '#d4e3ff',
        'secondary-fixed': '#ffe16d',
        'on-tertiary-container': '#f9ffec',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        tertiary: '#326800',
        'primary-container': '#0075d6',
        primary: '#005cab',
        'on-surface-variant': '#404753',
        'on-secondary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#255100',
        'tertiary-container': '#418400',
        'inverse-on-surface': '#f1f1f1',
        'inverse-primary': '#a5c8ff',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#001c3a',
        'surface-bright': '#f9f9f9',
        background: '#f9f9f9',
        'on-surface': '#1b1b1b',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'inverse-surface': '#303030',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'on-tertiary-fixed': '#0b2000',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#e9c400',
        'on-background': '#1b1b1b',
        'surface-tint': '#005faf',
        'on-secondary-fixed-variant': '#544600',
        'secondary-container': '#fcd400',
        'primary-fixed-dim': '#a5c8ff',
        'on-primary-fixed-variant': '#004786',
        'outline-variant': '#c0c7d6',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
        m3: '1rem',
        'm3-lg': '1.5rem',
      },
      boxShadow: {
        editorial: '0 32px 64px -12px rgba(27, 27, 27, 0.06)',
      },
      backdropBlur: {
        glass: '24px',
      },
    },
  },
  plugins: [],
};
